const visa_type_names = await fetch(
  "https://www.ivisa.com/product/reset-visa-type-names",
  {
    headers: {
      accept: "application/json, text/plain, */*",
      "accept-language": "en-US,en;q=0.9",
      "content-type": "application/json",
      priority: "u=1, i",
      "sec-ch-ua":
        '"Not:A-Brand";v="99", "Google Chrome";v="145", "Chromium";v="145"',
      "sec-ch-ua-mobile": "?0",
      "sec-ch-ua-platform": '"Windows"',
      "sec-fetch-dest": "empty",
      "sec-fetch-mode": "cors",
      "sec-fetch-site": "same-origin",
      "x-csrf-token": "",
      "x-requested-with": "XMLHttpRequest",
      cookie:
        "ceui=f818eyJpdiI6IjkvUlRaM0loTlNJR2RkYUFqdjFwR1E9PSIsInZhbHVlIjoiN1ZURU9NRDUzc2NxS2hUaElHbzU5aTY1RjY2cW5sRDZ2d0hRV0xYZkZlYjdyVTZVWG9LNldtdlQweXR1b0QxUHZ2Vm1rYWUrR3A3RkVrU0lXRGtGcWc9PSIsIm1hYyI6IjUzNzZhMTFhNzJiY2I0YjgxYWExYTU3N2ViNjYxNzJmNDU3MjljNjAxNTA1MmI0YzM2YzNkZjIxNWVkZTQ5YjIiLCJ0YWciOiIifQ%3D%3D; _ga=GA1.1.62096385.1771853093; _adora_user_id=019c8aac-ac8d-71fa-95ca-fb1173ab20c6; __stripe_mid=7485ed28-f083-4b8d-8f4c-8292c1a8652778dadc; _ga_80EH5PXLKX=GS2.1.s1771881367$o3$g1$t1771883483$j16$l0$h182078633$dvOYS5YUeTU1Exsm02pOuYS4s1GOlmq0Cdg; default_currency=USD; cbhint=seen; mostRecentVisaTypeIdViewed=5038; countryApplicationCode=PK; csid=f818eyJpdiI6Ik85NWpLWnk2a09qT2ZXeVdtTWlJSFE9PSIsInZhbHVlIjoibnhxK1d3aVhHV1Jwd2d4dDB3UWRRd2hqelZGZ2QrS3ZlNnRzMFFHNHZxd3ZuNWEwZHhlMVdoZFY0cXhEWFFyNTcydzhoTEdzL203NTQ3eGJzV0YwOTRTWjNmMXpWL3AwSjlMcXNCNHFwaVE9IiwibWFjIjoiZDE1NDQ5NDc1ZDFhNmU0OWJlODk1ZjJmMjAzY2ExZjkzZDg4MTY4YjcxNzlkN2I5MzQ2NmQwZmNlYzg4ZDg4YyIsInRhZyI6IiJ9; __stripe_sid=e43cb990-1997-4b9c-a7a8-06076bc60dcd2ac976; ceul=f818eyJpdiI6IkVvNGwramlNbE43eTRwNGhiOHNvT0E9PSIsInZhbHVlIjoiaVBSK2JlT21OSmlQcE55cnRDd0V2QzhwN3pRT2FvNXNtTkgvbi94SU4yZ29oRmZtNXo3SHd5QUZIM08yRHJuWUIyYWlDbFVVSE9vUnhJNWRBQWoyaE1nSzdyL21vZU9FL1Q3aXZNc1hpdms9IiwibWFjIjoiMWY4ZGQ1YzNjMzQ1NzZkMThkODg4NDVkZDRkODU0N2VjMGQ5YzYwNWEyOWRlMDFlMTgyN2FjYWY3MWY0MjNkMyIsInRhZyI6IiJ9; eafu=f818eyJpdiI6IjhRWVJFdjVNRmJ0Z05RRDErb3ZQR2c9PSIsInZhbHVlIjoieEswK1JjRFdjc2JuZFlEb0RValJqeklmWUl1ZjZiSzh4UUlqMmdQejhwdmtYWWVHcjcyQ1hWVytGNzJuRXdWb3Mxc3V1c3Y4Y3N3RHkzSlRsZURxbDRyMk5xS2YxNmxWYi96YldUb3EvSkk9IiwibWFjIjoiNDRjOWRkNWViYTU2ZjY4OThiNzQ1NjhmMzQ5YTQxZGRjYTI4ZTk3YTY0MTk1OGQ0M2Q1MzFkZDZkN2RkNzIzZSIsInRhZyI6IiJ9; applyLink=f818eyJpdiI6ImNRdkdBcHNQVnlGbEpJcnVBODBPQkE9PSIsInZhbHVlIjoiTjdPL21BalJnbm41Q2ZocmtoSmlpYVhvV1RmRmQrVjNPNUN2WlpyVnJjYTdBL2ZtRC96Zk9pcldsdWVyL2pwcG9OekVxTHBSNjA5RmYrNlBxTTNEOE93dFRtQ0dnVnQzRDZJdTJsQndlN3M3SHAzTFZqMGlHeEtjR3pDUXcra1N6M2owdk1CTXlnNDMwaHd4aE5WV2hBSURBYitNZjNpd2g2eTJRcElGSnBOZTdZcUVyNDFRZE0xM2FaM3VvNjk0IiwibWFjIjoiYmE0NjRiMTBjMWZmYjZiYzM4YWYyNWI0N2YwMTU2ZjBjZTdkODFkZTI5ZjBjMDlhMzlmZDdhZjNjZTIzNzAyYyIsInRhZyI6IiJ9; sabp=10141; cfzs_google-analytics_v4=%7B%22bbe7_conversionCounter%22%3A%7B%22v%22%3A%22724%22%7D%7D; cfz_zaraz-analytics=%7B%22_cfa_clientId%22%3A%7B%22v%22%3A%2237366920845453950%22%2C%22e%22%3A1803389088260%7D%2C%22_cfa_sId%22%3A%7B%22v%22%3A%2216180723804870866%22%2C%22e%22%3A1773078801759%7D%7D; cfz_google-analytics_v4=%7B%22bbe7_engagementDuration%22%3A%7B%22v%22%3A%220%22%2C%22e%22%3A1804607601759%7D%2C%22bbe7_engagementStart%22%3A%7B%22v%22%3A%221773071601759%22%2C%22e%22%3A1804607601759%7D%2C%22bbe7_counter%22%3A%7B%22v%22%3A%22881%22%2C%22e%22%3A1804607601759%7D%2C%22bbe7_session_counter%22%3A%7B%22v%22%3A%2213%22%2C%22e%22%3A1804607601759%7D%2C%22bbe7_ga4%22%3A%7B%22v%22%3A%22abde5ceb-4899-42ef-adf1-4cdb4e135839%22%2C%22e%22%3A1804607601759%7D%2C%22bbe7__z_ga_audiences%22%3A%7B%22v%22%3A%22abde5ceb-4899-42ef-adf1-4cdb4e135839%22%2C%22e%22%3A1803389088260%7D%2C%22bbe7_let%22%3A%7B%22v%22%3A%221773071601759%22%2C%22e%22%3A1804607601759%7D%2C%22bbe7_ga4sid%22%3A%7B%22v%22%3A%22780909996%22%2C%22e%22%3A1773073401759%7D%7D; _conv_v=vi%3A1*sc%3A15*cs%3A1773068254*fs%3A1771853088*pv%3A437*exp%3A%7B%7D*seg%3A%7B%7D*ps%3A1773065555; _conv_s=sh%3A1773068254301-0.5641237069223486*si%3A15*pv%3A84; nationalityFromPassport=AS",
      Referer: "https://www.ivisa.com/usa/apply-now",
    },
    body: JSON.stringify({
      global_fields: {
        common_nationality_country: "AS",
        product_add_ons: null,
        visa_type_id: null,
        num_applicants: 1,
        visa_processing_speed: null,
        phone: null,
        order_notification_signup: null,
        usa_travel_type: "No",
        hotel_info_us: null,
        destination_location_name: null,
        destination_address: null,
        destination_city: null,
        destination_state: null,
        destination_zip: null,
        destination_country: null,
        destination_phone: null,
        emergency_contact_us: null,
        emergency_contact_first_name: null,
        emergency_contact_last_name: null,
        emergency_contact_email: null,
        emergency_contact_phone: null,
        email: null,
        consent_to_marketing_emails: null,
      },
      traveler_list: [
        {
          first_name: null,
          last_name: null,
          dob: null,
          nationality_country: "AF",
          is_passport_on_hand: null,
          passport_num: null,
          passport_issued_date: null,
          passport_expiration_date: null,
          gender: null,
          birth_country: "AF",
          home_country: null,
          passport_10years_valid: null,
          national_identity_number: null,
          has_alias_name: "No",
          alias_first_name: null,
          alias_last_name: null,
          has_previous_nationality: "No",
          previous_nationality_country: null,
          secondary_nationality_acquisition: null,
          provide_details: null,
          hold_secondary_nationality: "No",
          previous_nationality: null,
          secondary_document_issued_country: null,
          previous_nationality_from: null,
          previous_nationality_to: null,
          which_statement_applies: null,
          secondary_nationality_us: null,
          last_document_number: null,
          other_document_expiration: null,
          member_cbp_global_entry_program: "No",
          cbp_membership_number: null,
          passport_issued_country: "AF",
          home_address: null,
          home_city: null,
          home_state: null,
          home_zip: null,
          are_employed:
            "Employed (including self-employed, freelancers, and business owners)",
          employer_name: null,
          employer_info_us: null,
          your_company_address: null,
          your_company_city: null,
          your_company_state: null,
          your_company_zip: null,
          your_company_country: null,
          applicable_statement: "I have information about both of my parents.",
          fathers_first_name: null,
          fathers_last_name: null,
          mothers_first_name: null,
          mothers_last_name: null,
          declarations_us: null,
          has_physical_or_mental_disorder: "No",
          convicted_of_crime_property_damage: "No",
          convicted_of_crime_drugs: "No",
          been_denied_us_visa: "No",
          date_of_event: null,
          denied_us_visa_place: null,
          has_overstayed_us: "No",
          been_conflict_area: "No",
          previous_trips: null,
          passport_photo: null,
          passport_scan: null,
        },
      ],
      primary_product_classification: "visa",
      quoted_total: "",
      currency: "USD",
      order_id: null,
      current_step: "step_1",
      experiment_ids: [],
      splitversion: "",
      time_zone: "Africa/Cairo",
      primary_product_id: 10141,
      destination_country_code: "EG", // what will be replaced with 2 letter country code
      stripe_payment_intent_ids: {
        braintree_dropin: null,
        spreedly_form: null,
        primer_dropin_checkout: null,
        elements: null,
        express_checkout: null,
      },
    }),
    method: "POST",
  },
);

// Response:
// {
//     options: [
//       {
//         name: 'India Tourist eVisa - 30 days, Double entry',
//         value: '5046',
//         show_if: [Object],
//         product_id: '10119',
//         eligible_nationalities: [Array],
//         product_name: 'India Tourist eVisa',
//         product_name_short: 'eVisa',
//         validity: [Object],
//         pricing: [Object],
//         id: 5046,
//         is_guided_entry: false
//       },
//       {
//         name: 'India e-Arrival Card - 30 days, Single entry',
//         value: '5629',
//         show_if: [Object],
//         product_id: '11121',
//         eligible_nationalities: [Array],
//         product_name: 'India e-Arrival Card',
//         product_name_short: 'Arrival Card',
//         validity: [Object],
//         pricing: [Object],
//         id: 5629,
//         is_guided_entry: false
//       },
//       {
//         name: 'India Tourist eVisa - 1 year, Multiple entry',
//         value: '21',
//         show_if: [Object],
//         product_id: '10119',
//         eligible_nationalities: [Array],
//         product_name: 'India Tourist eVisa',
//         product_name_short: 'eVisa',
//         validity: [Object],
//         pricing: [Object],
//         id: 21,
//         is_guided_entry: false
//       },
//       {
//         name: 'India Tourist eVisa - 5 years, Multiple entry',
//         value: '5047',
//         show_if: [Object],
//         product_id: '10119',
//         eligible_nationalities: [Array],
//         product_name: 'India Tourist eVisa',
//         product_name_short: 'eVisa',
//         validity: [Object],
//         pricing: [Object],
//         id: 5047,
//         is_guided_entry: false
//       },
//       {
//         name: 'India Business eVisa - 1 year, Multiple entry',
//         value: '22',
//         show_if: [Object],
//         product_id: '10120',
//         eligible_nationalities: [Array],
//         product_name: 'India Business eVisa',
//         product_name_short: 'eVisa',
//         validity: [Object],
//         pricing: [Object],
//         id: 22,
//         is_guided_entry: false
//       },
//       {
//         name: 'India Medical eVisa - 60 days, Triple entry',
//         value: '23',
//         show_if: [Object],
//         product_id: '10121',
//         eligible_nationalities: [Array],
//         product_name: 'India Medical eVisa',
//         product_name_short: 'eVisa',
//         validity: [Object],
//         pricing: [Object],
//         id: 23,
//         is_guided_entry: false
//       }
//     ]
//   }
//   each visa in this will have the following fields:
// {
//     "name": "India Tourist eVisa - 30 days, Double entry",
//     "value": "5046",
//     "show_if": {
//         "field_name": "common_nationality_country",
//         "condition": "in_list",
//         "value": [
//             "AX",
//             "AL",
//             "AS",
//             "AD",
//             "AO",
//             "AI",
//             "AG",
//             "AR",
//             "AM",
//             "AW",
//             "AU",
//             "AT",
//             "AZ",
//             "BS",
//             "BH",
//             "BB",
//             "BE",
//             "BZ",
//             "BJ",
//             "BO",
//             "BQ",
//             "BA",
//             "BW",
//             "BR",
//             "BN",
//             "BG",
//             "KH",
//             "CM",
//             "CA",
//             "CV",
//             "KY",
//             "CL",
//             "CX",
//             "CC",
//             "CO",
//             "KM",
//             "CK",
//             "CR",
//             "CI",
//             "HR",
//             "CW",
//             "CY",
//             "CZ",
//             "DK",
//             "DJ",
//             "DM",
//             "DO",
//             "TL",
//             "EC",
//             "SV",
//             "GQ",
//             "EE",
//             "FO",
//             "FJ",
//             "FI",
//             "FR",
//             "GF",
//             "PF",
//             "TF",
//         ]
//     },
//     "product_id": "10119",
//     "eligible_nationalities": [
//         "AX",
//         "AL",
//         "AS",
//         "AD",
//         "AO",
//         "AI",
//         "AG",
//         "AR",
//         "AM",
//         "AW",
//         "AU",
//         "AT",
//         "AZ",
//         "BS",
//         "BH",
//         "BB",
//         "BE",
//         "BZ",
//         "BJ",
//         "BO",
//         "BQ",
//         "BA",
//         "BW",
//         "BR",
//         "BN",
//         "BG",
//         "KH",
//         "CM",
//         "CA",
//         "CV",
//         "KY",
//         "CL",
//         "CX",
//         "CC",
//         "CO",
//         "KM",
//         "CK",
//         "CR",
//         "CI",
//         "HR",
//         "CW",
//         "CY",
//         "CZ",
//         "DK",
//         "DJ",
//         "DM",
//         "DO",
//         "TL",
//         "EC",
//         "SV",
//         "GQ",
//         "EE",
//         "FO",
//         "FJ",
//         "FI",
//         "FR",
//         "GF",
//         "PF",
//         "TF",
//     ],
//     "product_name": "India Tourist eVisa",
//     "product_name_short": "eVisa",
//     "validity": {
//         "visa_validity_days": 30,
//         "visa_validity": "30 days after arrival",
//         "num_entries": "Double entry",
//         "max_stay": "30 days in total",
//         "max_stay_short": "30 days",
//         "passport_requirements": {
//             "duration": 6,
//             "unit": "months",
//             "exp_type": "arrival"
//         },
//         "important_information_1": null,
//         "important_information_2": null,
//         "requirement_text": {
//             "product": "India Tourist eVisa",
//             "nationality": "American Samoa",
//             "destination": "India",
//             "optional": false
//         },
//         "gov_fee": "26",
//         "duration_string_translated": "30 days"
//     },
//     "pricing": {
//         "visa_cost": "26.00",
//         "visa_cost_pretty": "USD $26.00",
//         "name": "Government Fee",
//         "price_append": "Pay To iVisa",
//         "is_visa_cost_paid_later": false
//     },
//     "id": 5046,
//     "is_guided_entry": false
// }

console.log(await visa_type_names.json());

const productAvailability = await fetch(
  "https://www.ivisa.com/visa/product-availability-results/EG/USD/US", // it will be https://www.ivisa.com/visa/product-availability-results/nationality/USD/destination
  {
    headers: {
      accept: "application/json, text/plain, */*",
      "sec-ch-ua":
        '"Not:A-Brand";v="99", "Google Chrome";v="145", "Chromium";v="145"',
      "sec-ch-ua-mobile": "?0",
      "sec-ch-ua-platform": '"Windows"',
      "x-csrf-token": "",
      "x-requested-with": "XMLHttpRequest",
      Referer: "https://www.ivisa.com/india/apply-now",
    },
    body: null,
    method: "GET",
  },
);
// Response:
// {
//     visas_available: true,
//     product_qty: 1,
//     outcome: 'visa_supported',  (either: visa_supported, visa_needed_but_unsupported, no_visa_needed)
//     nationality: 'EG',
//     destination: 'US',
//     filter_bar_data: {
//       allFrom: [
//         [Object], [Object], [Object], [Object], [Object], [Object],
//         [Object], [Object], [Object], [Object], [Object], [Object],
//         [Object], [Object], [Object], [Object], [Object], [Object],
//         [Object], [Object], [Object], [Object], [Object], [Object],
//         [Object], [Object], [Object], [Object], [Object], [Object],
//         [Object], [Object], [Object], [Object], [Object], [Object],
//         [Object], [Object], [Object], [Object], [Object], [Object],
//         [Object], [Object], [Object], [Object], [Object], [Object],
//         [Object], [Object], [Object], [Object], [Object], [Object],
//         [Object], [Object], [Object], [Object], [Object], [Object],
//         [Object], [Object], [Object], [Object], [Object], [Object],
//         [Object], [Object], [Object], [Object], [Object], [Object],
//         [Object], [Object], [Object], [Object], [Object], [Object],
//         [Object], [Object], [Object], [Object], [Object], [Object],
//         [Object], [Object], [Object], [Object], [Object], [Object],
//         [Object], [Object], [Object], [Object], [Object], [Object],
//         [Object], [Object], [Object], [Object],
//         ... 150 more items
//       ],
//       allTo: [
//         [Object], [Object], [Object], [Object], [Object], [Object],
//         [Object], [Object], [Object], [Object], [Object], [Object],
//         [Object], [Object], [Object], [Object], [Object], [Object],
//         [Object], [Object], [Object], [Object], [Object], [Object],
//         [Object], [Object], [Object], [Object], [Object], [Object],
//         [Object], [Object], [Object], [Object], [Object], [Object],
//         [Object], [Object], [Object], [Object], [Object], [Object],
//         [Object], [Object], [Object], [Object], [Object], [Object],
//         [Object], [Object], [Object], [Object], [Object], [Object],
//         [Object], [Object], [Object], [Object], [Object], [Object],
//         [Object], [Object], [Object], [Object], [Object], [Object],
//         [Object], [Object], [Object], [Object], [Object], [Object],
//         [Object], [Object], [Object], [Object], [Object], [Object],
//         [Object], [Object], [Object], [Object], [Object], [Object],
//         [Object], [Object], [Object], [Object], [Object], [Object],
//         [Object], [Object], [Object], [Object], [Object], [Object],
//         [Object], [Object], [Object], [Object],
//         ... 150 more items
//       ],
//       popularfrom: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
//       popularto: [ [Object], [Object], [Object], [Object], [Object], [Object] ]
//     },
//     cards: [
//       {
//         title: 'Visa',
//         card_group: 'visa',
//         is_required: true,
//         color_scheme: 'red',
//         color_scheme_widget: 'yellow',
//         sub_title_text: 'The World Cup USA Visa is mandatory for Egypt passport holders traveling to United States.',
//         requirement_slug: 'required_for_travel',
//         requirement_level: 'Required For Travel',
//         requirement_level_widget: 'Required For Travel',
//         body_text: [Object],
//         tile_groups: [Object],
//         application_page_banner_title: 'Visa required',
//         sort_weight: 8
//       }
//     ],
//     reasons_for_travel: [ 'all', 'events' ],
//     initial_filter: 'events',
//     pretty_reasons: {
//       any: 'Any',
//       tourism: 'Tourism',
//       business: 'Business',
//       medical_treatment: 'Medical Treatment',
//       student: 'Student',
//       transit: 'Transit',
//       immigration: 'Immigration',
//       nomad: 'Nomad',
//       refugee: 'Refugee',
//       events: 'Events',
//       all: 'All'
//     }
//   }
console.log(await productAvailability.json());

const prices = await fetch("https://www.ivisa.com/product/processing_time", {
  headers: {
    accept: "application/json, text/plain, */*",
    "accept-language": "en-US,en;q=0.9",
    "content-type": "application/json",
    priority: "u=1, i",
    "sec-ch-ua":
      '"Not:A-Brand";v="99", "Google Chrome";v="145", "Chromium";v="145"',
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": '"Windows"',
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "x-csrf-token": "",
    "x-requested-with": "XMLHttpRequest",
    cookie:
      "ceui=f818eyJpdiI6IjkvUlRaM0loTlNJR2RkYUFqdjFwR1E9PSIsInZhbHVlIjoiN1ZURU9NRDUzc2NxS2hUaElHbzU5aTY1RjY2cW5sRDZ2d0hRV0xYZkZlYjdyVTZVWG9LNldtdlQweXR1b0QxUHZ2Vm1rYWUrR3A3RkVrU0lXRGtGcWc9PSIsIm1hYyI6IjUzNzZhMTFhNzJiY2I0YjgxYWExYTU3N2ViNjYxNzJmNDU3MjljNjAxNTA1MmI0YzM2YzNkZjIxNWVkZTQ5YjIiLCJ0YWciOiIifQ%3D%3D; _ga=GA1.1.62096385.1771853093; _adora_user_id=019c8aac-ac8d-71fa-95ca-fb1173ab20c6; __stripe_mid=7485ed28-f083-4b8d-8f4c-8292c1a8652778dadc; _ga_80EH5PXLKX=GS2.1.s1771881367$o3$g1$t1771883483$j16$l0$h182078633$dvOYS5YUeTU1Exsm02pOuYS4s1GOlmq0Cdg; default_currency=USD; cbhint=seen; mostRecentVisaTypeIdViewed=5038; countryApplicationCode=PK; csid=f818eyJpdiI6Ik85NWpLWnk2a09qT2ZXeVdtTWlJSFE9PSIsInZhbHVlIjoibnhxK1d3aVhHV1Jwd2d4dDB3UWRRd2hqelZGZ2QrS3ZlNnRzMFFHNHZxd3ZuNWEwZHhlMVdoZFY0cXhEWFFyNTcydzhoTEdzL203NTQ3eGJzV0YwOTRTWjNmMXpWL3AwSjlMcXNCNHFwaVE9IiwibWFjIjoiZDE1NDQ5NDc1ZDFhNmU0OWJlODk1ZjJmMjAzY2ExZjkzZDg4MTY4YjcxNzlkN2I5MzQ2NmQwZmNlYzg4ZDg4YyIsInRhZyI6IiJ9; __stripe_sid=e43cb990-1997-4b9c-a7a8-06076bc60dcd2ac976; ceul=f818eyJpdiI6InkzSTF0MWl2MGV3ZnluYStYczdQNXc9PSIsInZhbHVlIjoidzZSWFQ2Zi91SXdUVzU0SGtqTk1abGk0TnBUVHMzZE03RDJ5YjlkeHFPcDBSYko0TjNVa3pFWUU5eFNKWThIZldvR0N2bm9Td2dQR0trRXBZa2lnK05seFJ4YTR1djRITm1GYnBZLzV3ZTA9IiwibWFjIjoiNGJhZjYxZThlMGYxZjBhZjBlMTg0ZjU5OTVmM2NlYzQwZDRlMjM2MWVhYmQyNmQ1OGE0N2U5Nzc3OTQ2ZjIwYyIsInRhZyI6IiJ9; sabp=10173; nationalityFromPassport=DZ; _conv_v=vi%3A1*sc%3A15*cs%3A1773068254*fs%3A1771853088*pv%3A419*exp%3A%7B%7D*seg%3A%7B%7D*ps%3A1773065555; _conv_s=sh%3A1773068254301-0.5641237069223486*si%3A15*pv%3A66; eafu=f818eyJpdiI6Imc2ZjF3amZFSmNqUFpIM3lvMHk5RXc9PSIsInZhbHVlIjoickZqUERhMHdubEFZQ3hCQmNMajJwNU1BV3d5bFhoK0ptS2M1Ym9oVUlXQ3U0VnVoRkN4RlkyekVZTmxldmV5MzFmd1lXUG9ZMWNBNXJ3b0pJUzFGalV6Wm9saEh4c2NORUJ1VThMeVVpaWM9IiwibWFjIjoiM2MwMzk1YmY4YmIwZjJjNDViZmE3ZDA4NTJjMDQ5OGM0MmUxMDEyODY0MDg0NmIwZTJkY2YwMDY4YTQzOTNkZiIsInRhZyI6IiJ9; applyLink=f818eyJpdiI6IlFaSlV2aGJqbEhSaTIwbEJHUTQzbUE9PSIsInZhbHVlIjoidU5KOFJ3bW9YdGtuSU4wZHU4d0lobkZrcTh2RmtrSmdteHFvK1VMQXErMzNyQld3SytEUHRXWkUyanQxMlFJL25oaWs0MHpVZlc1bCs4cVpLa2VmM3R3U2JsY1VLcENkajVTWG01SHpxR0FKNDNCNUV2dVAyZmJlTmVUOVUyOG5MUnVqdnJxb1pIRmtNQ1hQYU1OZXg2YmhudVhHZ3Z5aEp3TEM0cDdORnRZTkJRK01Pdi9oRzVMeXNYTU9TWnNWIiwibWFjIjoiNGNhMzg4YmI1NDVhNjgxZDc5YzgwNzI3MWFiNzhlZmM5ZDQxZTQ4MzFlNTc4M2U4ZGVjNDUzNDczODNhNjNhNCIsInRhZyI6IiJ9; cfzs_google-analytics_v4=%7B%22bbe7_conversionCounter%22%3A%7B%22v%22%3A%22680%22%7D%7D; cfz_zaraz-analytics=%7B%22_cfa_clientId%22%3A%7B%22v%22%3A%2237366920845453950%22%2C%22e%22%3A1803389088260%7D%2C%22_cfa_sId%22%3A%7B%22v%22%3A%2216180723804870866%22%2C%22e%22%3A1773077912535%7D%7D; cfz_google-analytics_v4=%7B%22bbe7_engagementDuration%22%3A%7B%22v%22%3A%220%22%2C%22e%22%3A1804606712535%7D%2C%22bbe7_engagementStart%22%3A%7B%22v%22%3A%221773070712535%22%2C%22e%22%3A1804606712535%7D%2C%22bbe7_counter%22%3A%7B%22v%22%3A%22837%22%2C%22e%22%3A1804606712535%7D%2C%22bbe7_session_counter%22%3A%7B%22v%22%3A%2213%22%2C%22e%22%3A1804606712535%7D%2C%22bbe7_ga4%22%3A%7B%22v%22%3A%22abde5ceb-4899-42ef-adf1-4cdb4e135839%22%2C%22e%22%3A1804606712535%7D%2C%22bbe7__z_ga_audiences%22%3A%7B%22v%22%3A%22abde5ceb-4899-42ef-adf1-4cdb4e135839%22%2C%22e%22%3A1803389088260%7D%2C%22bbe7_let%22%3A%7B%22v%22%3A%221773070712535%22%2C%22e%22%3A1804606712535%7D%2C%22bbe7_ga4sid%22%3A%7B%22v%22%3A%22780909996%22%2C%22e%22%3A1773072512535%7D%7D",
    Referer: "https://www.ivisa.com/armenia/apply-now",
  },
  body: JSON.stringify({
    global_fields: {
      common_nationality_country: "GB",
      product_add_ons: null,
      visa_type_id: "16",
      visa_processing_speed: null,
      phone: null,
      order_notification_signup: null,
      arrival_date: null,
      departure_date: null,
      num_applicants: 1,
      reason_for_travel: "Tourism / Visit Relative / Friend",
      destination_state: null,
      destination_address: null,
      destination_city: null,
      destination_zip: null,
      destination_country: null,
      destination_phone: null,
      email: "anashesham000@gmail.com",
      consent_to_marketing_emails: null,
    },
    traveler_list: [
      {
        first_name: "Anas",
        last_name: "Mohamed",
        dob: "1979-01-04",
        nationality_country: "GB",
        is_passport_on_hand: true,
        passport_num: null,
        passport_issued_date: null,
        passport_expiration_date: null,
        gender: null,
        home_address: null,
        home_city: null,
        home_state: null,
        home_zip: null,
        which_statement_applies: null,
        home_country: null,
        birth_country: "GB",
        occupation: null,
        last_departure_city: null,
        arrival_city: null,
        arrival_flight_number: null,
        departure_city: null,
        departure_flight_number: null,
        convicted_criminal: "No",
        passport_photo: null,
        passport_scan: null,
        bank_statements: null,
        travel_medical_insurance_proof: null,
        bank_statement_3months: null,
        proof_residence_mar: null,
        valid_visa_mar: null,
        return_ticket: null,
      },
    ],
    primary_product_classification: "visa",
    quoted_total: "58.45",
    currency: "USD",
    order_id: null,
    current_step: "review",
    experiment_ids: [],
    splitversion: "",
    time_zone: "Africa/Cairo",
    primary_product_id: "10173",
    destination_country_code: "EG",
    stripe_payment_intent_ids: {
      braintree_dropin: null,
      spreedly_form: null,
      primer_dropin_checkout: null,
      elements: null,
      express_checkout: null,
    },
  }),
  method: "POST",
});
// Response:
// [
//   {
//     time: "6 days",
//     available: "service available M-F 9am-5pm ET",
//     time_minutes: 8640,
//     disable_nationalities: [],
//     disabled: false,
//     name_pretty: "Standard - 6 days",
//     code: "standard",
//     earliest_delivery: "Sun, Mar 15, 2026",
//     earliest_delivery_sidebar: "Sun, Mar 15, 2026",
//     earliest_delivery_widget: "March 15, 2026",
//     price: 79.99,
//     price_per_applicant: 79.99,  // this is what matters and it will be the processing_fee
//     price_per_applicant_with_discount: 79.99,
//     price_pretty: "USD $79.99",
//     price_pretty_with_discount: "USD $79.99",
//     price_with_currency_symbol: "$79.99",
//     price_with_fee_included_pretty: "$159.98",
//     visa_cost_pretty: "$25.00",
//     price_usd: 79.99,
//     price_with_discount: 79.99,
//     price_with_visa_cost_pretty: "USD $79.99",
//     processing_label: "6 day processing",
//     processing_speed_int: 0,
//     processing_type: "Standard",
//     warning_body: "",
//     warning_title: null,
//     will_be_queued: false,
//     price_per_applicant_pretty: "$79.99",
//     price_per_applicant_with_discount_pretty: "$79.99",
//   },
// ];
const data = await prices.json();
console.log(data[0]);
